// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RespData.proto
// Protobuf Java Version: 4.33.1

package org.laz.floruitid.floruitclient.model.resp;

@com.google.protobuf.Generated
public final class RespDataOuter extends com.google.protobuf.GeneratedFile {
    private RespDataOuter() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 33,
                /* patch= */ 1,
                /* suffix= */ "",
                "RespDataOuter");
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_laz_floruitid_model_resp_RespData_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_org_laz_floruitid_model_resp_RespData_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\016RespData.proto\022\034org.laz.floruitid.mode" +
                        "l.resp\"L\n\010RespData\022\r\n\005reqId\030\001 \001(\003\022\017\n\007suc" +
                        "cess\030\002 \001(\010\022\017\n\007message\030\003 \001(\t\022\017\n\007content\030\004" +
                        " \001(\tB=\n*org.laz.floruitid.floruitclient." +
                        "model.respB\rRespDataOuterP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_org_laz_floruitid_model_resp_RespData_descriptor =
                getDescriptor().getMessageType(0);
        internal_static_org_laz_floruitid_model_resp_RespData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_org_laz_floruitid_model_resp_RespData_descriptor,
                new String[]{"ReqId", "Success", "Message", "Content",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
