// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RespData.proto
// Protobuf Java Version: 4.33.1

package org.laz.floruitid.floruitclient.model.resp;

/**
 * Protobuf type {@code org.laz.floruitid.model.resp.RespData}
 */
@com.google.protobuf.Generated
public final class RespData extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:org.laz.floruitid.model.resp.RespData)
        RespDataOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 33,
                /* patch= */ 1,
                /* suffix= */ "",
                "RespData");
    }

    // Use RespData.newBuilder() to construct.
    private RespData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private RespData() {
        message_ = "";
        content_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return RespDataOuter.internal_static_org_laz_floruitid_model_resp_RespData_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return RespDataOuter.internal_static_org_laz_floruitid_model_resp_RespData_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        RespData.class, Builder.class);
    }

    public static final int REQID_FIELD_NUMBER = 1;
    private long reqId_ = 0L;

    /**
     * <code>int64 reqId = 1;</code>
     *
     * @return The reqId.
     */
    @Override
    public long getReqId() {
        return reqId_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_ = false;

    /**
     * <code>bool success = 2;</code>
     *
     * @return The success.
     */
    @Override
    public boolean getSuccess() {
        return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object message_ = "";

    /**
     * <code>string message = 3;</code>
     *
     * @return The message.
     */
    @Override
    public String getMessage() {
        Object ref = message_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            message_ = s;
            return s;
        }
    }

    /**
     * <code>string message = 3;</code>
     *
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
    getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            message_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object content_ = "";

    /**
     * <code>string content = 4;</code>
     *
     * @return The content.
     */
    @Override
    public String getContent() {
        Object ref = content_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            content_ = s;
            return s;
        }
    }

    /**
     * <code>string content = 4;</code>
     *
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
    getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            content_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (reqId_ != 0L) {
            output.writeInt64(1, reqId_);
        }
        if (success_ != false) {
            output.writeBool(2, success_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 3, message_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 4, content_);
        }
        getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (reqId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, reqId_);
        }
        if (success_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(2, success_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(3, message_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(4, content_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof RespData)) {
            return super.equals(obj);
        }
        RespData other = (RespData) obj;

        if (getReqId()
                != other.getReqId()) return false;
        if (getSuccess()
                != other.getSuccess()) return false;
        if (!getMessage()
                .equals(other.getMessage())) return false;
        if (!getContent()
                .equals(other.getContent())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + REQID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getReqId());
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getSuccess());
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static RespData parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static RespData parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static RespData parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static RespData parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static RespData parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static RespData parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static RespData parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static RespData parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static RespData parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static RespData parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static RespData parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static RespData parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(RespData prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code org.laz.floruitid.model.resp.RespData}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:org.laz.floruitid.model.resp.RespData)
            RespDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return RespDataOuter.internal_static_org_laz_floruitid_model_resp_RespData_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return RespDataOuter.internal_static_org_laz_floruitid_model_resp_RespData_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            RespData.class, Builder.class);
        }

        // Construct using org.laz.floruitid.floruitclient.model.resp.RespData.newBuilder()
        private Builder() {

        }

        private Builder(
                BuilderParent parent) {
            super(parent);

        }

        @Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            reqId_ = 0L;
            success_ = false;
            message_ = "";
            content_ = "";
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return RespDataOuter.internal_static_org_laz_floruitid_model_resp_RespData_descriptor;
        }

        @Override
        public RespData getDefaultInstanceForType() {
            return RespData.getDefaultInstance();
        }

        @Override
        public RespData build() {
            RespData result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public RespData buildPartial() {
            RespData result = new RespData(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(RespData result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.reqId_ = reqId_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.success_ = success_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.message_ = message_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.content_ = content_;
            }
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof RespData) {
                return mergeFrom((RespData) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(RespData other) {
            if (other == RespData.getDefaultInstance()) return this;
            if (other.getReqId() != 0L) {
                setReqId(other.getReqId());
            }
            if (other.getSuccess() != false) {
                setSuccess(other.getSuccess());
            }
            if (!other.getMessage().isEmpty()) {
                message_ = other.message_;
                bitField0_ |= 0x00000004;
                onChanged();
            }
            if (!other.getContent().isEmpty()) {
                content_ = other.content_;
                bitField0_ |= 0x00000008;
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            reqId_ = input.readInt64();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 8
                        case 16: {
                            success_ = input.readBool();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 16
                        case 26: {
                            message_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 26
                        case 34: {
                            content_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 34
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private long reqId_;

        /**
         * <code>int64 reqId = 1;</code>
         *
         * @return The reqId.
         */
        @Override
        public long getReqId() {
            return reqId_;
        }

        /**
         * <code>int64 reqId = 1;</code>
         *
         * @param value The reqId to set.
         * @return This builder for chaining.
         */
        public Builder setReqId(long value) {

            reqId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>int64 reqId = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearReqId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            reqId_ = 0L;
            onChanged();
            return this;
        }

        private boolean success_;

        /**
         * <code>bool success = 2;</code>
         *
         * @return The success.
         */
        @Override
        public boolean getSuccess() {
            return success_;
        }

        /**
         * <code>bool success = 2;</code>
         *
         * @param value The success to set.
         * @return This builder for chaining.
         */
        public Builder setSuccess(boolean value) {

            success_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>bool success = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSuccess() {
            bitField0_ = (bitField0_ & ~0x00000002);
            success_ = false;
            onChanged();
            return this;
        }

        private Object message_ = "";

        /**
         * <code>string message = 3;</code>
         *
         * @return The message.
         */
        public String getMessage() {
            Object ref = message_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                message_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string message = 3;</code>
         *
         * @return The bytes for message.
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            Object ref = message_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string message = 3;</code>
         *
         * @param value The message to set.
         * @return This builder for chaining.
         */
        public Builder setMessage(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            message_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>string message = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMessage() {
            message_ = getDefaultInstance().getMessage();
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }

        /**
         * <code>string message = 3;</code>
         *
         * @param value The bytes for message to set.
         * @return This builder for chaining.
         */
        public Builder setMessageBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            message_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        private Object content_ = "";

        /**
         * <code>string content = 4;</code>
         *
         * @return The content.
         */
        public String getContent() {
            Object ref = content_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                content_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string content = 4;</code>
         *
         * @return The bytes for content.
         */
        public com.google.protobuf.ByteString
        getContentBytes() {
            Object ref = content_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string content = 4;</code>
         *
         * @param value The content to set.
         * @return This builder for chaining.
         */
        public Builder setContent(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            content_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>string content = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearContent() {
            content_ = getDefaultInstance().getContent();
            bitField0_ = (bitField0_ & ~0x00000008);
            onChanged();
            return this;
        }

        /**
         * <code>string content = 4;</code>
         *
         * @param value The bytes for content to set.
         * @return This builder for chaining.
         */
        public Builder setContentBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            content_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:org.laz.floruitid.model.resp.RespData)
    }

    // @@protoc_insertion_point(class_scope:org.laz.floruitid.model.resp.RespData)
    private static final RespData DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new RespData();
    }

    public static RespData getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RespData>
            PARSER = new com.google.protobuf.AbstractParser<RespData>() {
        @Override
        public RespData parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<RespData> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RespData> getParserForType() {
        return PARSER;
    }

    @Override
    public RespData getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

